apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackoverflow-spring
spec:
  selector:
    matchLabels:
      app: stackoverflow-spring
  replicas: 2
  template:
    metadata:
      labels:
        app: stackoverflow-spring
    spec:
      containers:
        - name: stackoverflow-spring
          image: shivamtech29/stackoverflow-spring:2.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: stackoverflow-spring-svc
spec:
  selector:
    app: stackoverflow-spring
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 5000
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stackoverflow-spring
spec:
  ingressClassName: istio
  rules:
    - host: stackoverflow-spring.b7b0cfd.kyma.ondemand.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stackoverflow-spring-svc
                port:
                  number: 8080
  tls:
    - hosts:
      - stackoverflow-spring.b7b0cfd.kyma.ondemand.com
      secretName: kyma-gateway-certs
